name: easy_shop
description: "EasyShop is a simple and clean e-commerce mobile application built for internship evaluation. It offers a user-friendly interface and essential shopping features such as product browsing, detailed views, cart management, and authentication."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3
  http: ^1.1.0
  json_annotation: ^4.8.1
  provider: ^6.1.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
